f7_techmonks_default_low_density:
  game: techmonks
  prompts:
  - prompts/techmonks
  - prompts/techmonks_1
  strategy_name: riot
  results_repo: metrics
  agent_name: opinion_llm
  ps:
    name: random_grid
  controlled_agent: -1
  bias_primer:
  - 0.4
  - 0.5
  - 0.6
  llm:
    model_type: llama
    model: ./models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
    temp: 0
    max_tokens: 100
    batch_size: 256
  grid_size:
  - 6
  - 8
  - 10
  num_rounds: 20
  seeds:
  - 42
  - 69
  - 100
  - 150
  - 1337