f8_techmonks_default_low_density_llama3:
  game: techmonks
  prompts:
  - prompts/techmonks
  - prompts/techmonks_1
  strategy_name: riot
  results_repo: metrics
  agent_name: opinion_llm
  ps:
    name: random_grid
  controlled_agent: -1
  bias_primer:
  - 0.1
  - 0.2
  - 0.3
  llm:
    model_type: llama
    model: ./models/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf
    temp: 0.0
    max_tokens: 100
    batch_size: 256
  grid_size:
  - 6
  - 8
  - 10
  num_rounds: 20
  seeds:
  - 42
  - 69
  - 100
  - 150
  - 1337